version: '3'
services:
  php:
    build:
      context: .
      dockerfile: .Dockerfile-php
    volumes:
      - ./seu_codigo_php:/var/www/html
    networks:
      - app-network

  apache:
    build:
      context: .
      dockerfile: .Dockerfile-apache
    ports:
      - "9090:80"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  farmacia-postgres:
    container_name: bd-postgres
    image: postgres
    restart: always
    volumes:
      - .docker/postgres:/var/lib/postgresql
      - ./app/db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
